baseURL = 'https://Applequist.github.io/'
languageCode = 'en-us'
title = 'brieuc.desoutter'
theme = 'basic'
copyright = '(c) 2024 Brieuc Desoutter'

[Params]
author = 'Brieuc Desoutter'
description = 'The personal website of Brieuc Desoutter.'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'catppuccin-latte'
tabWidth = 2

